#./ath9khtc-nightly.sh
#./distro-nightly.sh
#./fbtundebconfig.sh
./fbtunnel-nightly.sh
#./gumbop-nightly.sh
#./i2pd-nightly.sh
#./i2p-nightly.sh
./libsodium-nightly.sh
./libtoxcore-nightly.sh
./pidgingnomekeyring-nightly.sh
./twisterd-nightly.sh
#./(UNFINISHED)twisterhtm-nightly.sh
